### ISSUE TITLE
DuckDB server tree error

### ISSUE THREAD

**Issue by greg-fittus** [timeseries/qstudio#14]
<img width="960" alt="image" src="https://github.com/timeseries/qstudioopen/assets/141731699/a361eb2c-03c1-4be6-97b2-3572e38d3eba">

```

Details:

OS=Windows 8.1
Java=11.0.20
Des=unknown
Stack=java.lang.NullPointerException
	at java.desktop/javax.swing.JLabel.setIcon(Unknown Source)
	at com.timestored.qstudio.servertree.CustomNode$CustomNodeRenderer.getTreeCellRendererComponent(CustomNode.java:108)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(Unknown Source)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(Unknown Source)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(Unknown Source)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.updateNodeSizes(Unknown Source)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.invalidateSizes(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.setCellRenderer(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.propertyChange(Unknown Source)
	at com.formdev.flatlaf.ui.FlatTreeUI.lambda$createPropertyChangeListener$0(FlatTreeUI.java:307)
	at java.desktop/java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/java.awt.Component.firePropertyChange(Unknown Source)
	at java.desktop/javax.swing.JTree.setCellRenderer(Unknown Source)
	at com.timestored.qstudio.servertree.CustomNode.configure(CustomNode.java:74)
	at com.timestored.qstudio.servertree.ServerListPanel.refreshGui(ServerListPanel.java:171)
	at com.timestored.qstudio.servertree.ServerListPanel.modelChanged(ServerListPanel.java:182)
	at com.timestored.qstudio.model.AdminModel.refresh(AdminModel.java:223)
	at com.timestored.qstudio.model.AdminModel.access$600(AdminModel.java:27)
	at com.timestored.qstudio.model.AdminModel$3.run(AdminModel.java:380)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by greg-fittus** [comment]
Was deleting connections when issue occured

**Comment by ryanhamilton** [comment]
Hi Greg,

Thanks for the info. I tried recreating this and couldn't. 
I also checked the code and it checks for nulls just before the trace you sent:
https://github.com/timeseries/qstudio/blob/master/qstudio/src/main/java/com/timestored/qstudio/servertree/CustomNode.java#L123

Does this happen regularly?
