### ISSUE TITLE
Suggestions for main qStudio web site

### ISSUE THREAD

**Issue by richb-hanover** [timeseries/qstudio#72]
@ryanhamilton I have several suggestions for edits to the main qStudio web site https://www.timestored.com/qstudio/ and its sub-pages.

Are you open to these? What's the best way to submit them? Thanks.

**Comment by richb-hanover** [comment]
@ryanhamilton **Update:** I did some spelunking, and searched my hard drive for "qstudio". I found a log file from today named _/Users/richb/qstudio/log0.log.1_ . Observations:

* PATH when double-clicked: `PATH = /usr/bin:/bin:/usr/sbin:/sbin` 
* PATH when launched with `java -jar qstudio.jar`: `PATH = /Users/richb/.local/bin:/Applications/Tools-Developer/Racket:/Users/richb/.pyenv/shims:/Users/richb/.pyenv/bin:/Users/richb/.deno/bin:/Users/richb/.pyenv/bin:/Users/richb/.nvm/versions/node/v20.9.0/bin:/Users/richb/.cargo/bin:/opt/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin:/usr/libexec:/Applications/Tools-Developer/Racket/bin:/Users/richb/.rvm/bin` when launched with `java -jar qstudio.jar`

```
Sep 15, 2024 10:01:39 AM com.timestored.docs.BackgroundDocumentsSaver saveDocumentsScratch
INFO: Saving docs to scratch
... starting today ...
Sep 23, 2024 6:55:08 AM com.timestored.qstudio.QStudioLauncher$2 launch
INFO: Starting QStudioLauncher  launch() ###################################
Sep 23, 2024 6:55:08 AM com.timestored.qstudio.QStudioLauncher$2 launch
INFO: version = 3.10
Sep 23, 2024 6:55:08 AM com.timestored.qstudio.QStudioLauncher$2 launch
INFO: current dir = /Applications/.
Sep 23, 2024 6:55:08 AM com.timestored.qstudio.QStudioLauncher$2 launch
INFO: PATH = /usr/bin:/bin:/usr/sbin:/sbin
Sep 23, 2024 6:55:08 AM com.timestored.qstudio.QStudioLauncher$2 launch
INFO: JAVA_HOME = null
Sep 23, 2024 6:55:08 AM com.timestored.qstudio.QStudioLauncher$2 launch
INFO: java.version =16.0.1
Sep 23, 2024 6:55:08 AM com.timestored.qstudio.QStudioLauncher$2 launch
INFO: os.name =Mac OS X
Sep 23, 2024 6:55:08 AM com.timestored.qstudio.QStudioLauncher$2 launch
INFO: user.home =/Users/richb
Sep 23, 2024 6:55:08 AM com.timestored.qstudio.QStudioLauncher$2 launch
INFO: user.dir =/Applications
Sep 23, 2024 6:55:08 AM com.timestored.connections.ConnectionManager reloadFromPreferences
WARNING: stored conns and current conns disagreed, using stored values
Sep 23, 2024 6:55:08 AM com.timestored.connections.ConnectionManager reloadFromPreferences
WARNING: serverConns = []
Sep 23, 2024 6:55:08 AM com.timestored.connections.ConnectionManager reloadFromPreferences
WARNING: sConns = [ServerConfig{name=\Users\richb\github\TaxFairness\Property_In_Lyme.sqlite, username=, host=localhost, port=0, cstoreType=SQLITE_JDBC, database=jdbc:sqlite:/Users/richb/github/TaxFairness/Property_In_Lyme.sqlite}]
Sep 23, 2024 6:55:08 AM com.timestored.qstudio.QStudioFrame <init>
INFO: Starting QStudioFrame Constructor
Sep 23, 2024 6:55:09 AM com.timestored.swingxx.FileTreePanel refreshGui
INFO: FileTreePanel refreshGui
Sep 23, 2024 6:55:09 AM com.timestored.swingxx.FileTreePanel refreshGui
INFO: FileTreePanel refreshGui
Sep 23, 2024 6:55:09 AM com.timestored.qstudio.servertree.ServerListPanel refreshGui
INFO: refreshGui
Sep 23, 2024 6:55:09 AM com.timestored.sqldash.model.AbstractWidget configChanged
INFO: Widget 0 configChanged
Sep 23, 2024 6:55:09 AM com.timestored.sqldash.model.AbstractWidget configChanged
INFO: Widget 0 configChanged
Sep 23, 2024 6:55:09 AM com.timestored.swingxx.FileTreePanel refreshGui
INFO: FileTreePanel refreshGui
Sep 23, 2024 6:55:10 AM com.timestored.qstudio.model.AdminModel refresh
INFO: AdminModel hard Refresh
Sep 23, 2024 6:55:10 AM com.timestored.qstudio.QStudioFrame <init>
INFO: Finished QStudioFrame Constructor
Sep 23, 2024 6:55:10 AM com.timestored.qstudio.servertree.ServerListPanel refreshGui
INFO: refreshGui
Sep 23, 2024 6:55:10 AM com.timestored.docs.OpenDocumentsModel setSelectedFolder
INFO: setSelectedFolder: null
Sep 23, 2024 6:55:10 AM com.timestored.docs.BackgroundDocumentsSaver restoreDocuments
INFO: attempting to restore existing known document
Sep 23, 2024 6:55:10 AM com.timestored.docs.OpenDocumentsModel openDocument
INFO: openDocument: CU_Appr_vs_Ass.prql
Sep 23, 2024 6:55:10 AM com.timestored.docs.OpenDocumentsModel setSelectedDocument
INFO: setSelectedDocument: CU_Appr_vs_Ass.prql
Sep 23, 2024 6:55:10 AM com.timestored.docs.BackgroundDocumentsSaver restoreDocuments
INFO: attempting to restore existing known document
Sep 23, 2024 6:55:10 AM com.timestored.docs.OpenDocumentsModel openDocument
INFO: openDocument: Current Use less than improvements.prql
Sep 23, 2024 6:55:10 AM com.timestored.docs.OpenDocumentsModel setSelectedDocument
INFO: setSelectedDocument: Current Use less than improvements.prql
Sep 23, 2024 6:55:10 AM com.timestored.docs.OpenDocumentsModel closeDocument
INFO: closeDocument: new 1
Sep 23, 2024 6:55:10 AM com.timestored.qstudio.QStudioLauncher$2 launch
INFO: Ending QStudioLauncher launch()
Sep 23, 2024 6:55:10 AM com.timestored.docs.OpenDocumentsModel setSelectedDocument
INFO: setSelectedDocument: CU_Appr_vs_Ass.prql
Sep 23, 2024 6:55:10 AM com.timestored.plugins.PluginLoader getCClass
INFO: Could not find class already loaded. Refreshing from folders / jars.
Sep 23, 2024 6:55:11 AM com.timestored.connections.ConnectionManager statusUpdate
INFO: \Users\richb\github\TaxFairness\Property_In_Lyme.sqlite Connected = true
Sep 23, 2024 6:55:11 AM com.timestored.qstudio.servertree.ServerListPanel refreshGui
INFO: refreshGui
Sep 23, 2024 6:55:11 AM com.timestored.qstudio.model.AdminModel$2 run
INFO: refreshing \Users\richb\github\TaxFairness\Property_In_Lyme.sqlite
Sep 23, 2024 6:55:11 AM com.timestored.docs.OpenDocumentsModel setSelectedDocument
INFO: setSelectedDocument: Current Use less than improvements.prql
Sep 23, 2024 6:55:11 AM com.timestored.qstudio.servertree.ServerListPanel refreshGui
INFO: refreshGui
Sep 23, 2024 6:55:21 AM com.timestored.qstudio.CommonActions sendQuery
WARNING: Send Query Error
java.io.IOException: Cannot run program "prqlc": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.timestored.qstudio.CommonActions.compilePRQL(CommonActions.java:602)
	at com.timestored.qstudio.CommonActions.sendQuery(CommonActions.java:580)
	at com.timestored.qstudio.CommonActions.sendQuery(CommonActions.java:548)
	at com.timestored.qstudio.CommonActions.access$000(CommonActions.java:99)
	at com.timestored.qstudio.CommonActions$1.actionPerformed(CommonActions.java:176)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:354)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:977)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1809)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2900)
	at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:704)
	at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:711)
	at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:711)
	at java.desktop/javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:682)
	at java.desktop/javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:311)
	at java.desktop/javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:297)
	at java.desktop/javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2993)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2985)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
	at java.desktop/java.awt.Component.processEvent(Component.java:6394)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:875)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1144)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1014)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:840)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4874)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
	... 55 more

Sep 23, 2024 6:55:21 AM com.timestored.jgrowl.FadingGrowler show
SEVERE: Error: Problem sending query to server
Sep 23, 2024 6:55:21 AM com.timestored.qstudio.model.QueryManager sendQRtoListeners
INFO: queryResultReturned: QueryResult{query=# Current Use properties whose appraised improvements < assessed
# 14Feb2023
# NONE - WHEW!

prql target:sql.sqlite

# dollars displays a numeric value as dollars with commas
let dollars = d -> s"""printf("$%,d",{d})"""

# pct computes the amount (percent) the new differs from old
let pct = o n -> 100.0*( n - o ) / o

# prtpct prints a floating point number with "%"
let prtpct = v -> s'printf("%1.1f%", {v})'

let taxrate = 23.98

from sd = ScrapedData
filter (sd.SD_Version == 15)
select {
  Map=SD_Map,
  Lot=SD_Lot,
  Unit=SD_Unit,

  Adrs=SD_Street_Address,
  appr=SD_Appraisal2021,
  assm= SD_Assessment2021,
  apprImp = SD_App_Imp2021,
  taxAppr = appr*taxrate/1000,
  taxAssm = assm*taxrate/1000,

  delta= taxAppr - taxAssm,
  deltaprt = (dollars delta),
  pct = prtpct ( pct taxAssm taxAppr)
}
filter appr > 50_000
filter assm < apprImp
sort taxAssm / taxAppr

# select [
#   (dollars (sum delta))
# ], wasResult=false, wasException=true}
Sep 23, 2024 6:55:21 AM com.timestored.sqldash.model.AbstractWidget configChanged
INFO: Widget 0 configChanged
Sep 23, 2024 6:56:12 AM com.timestored.docs.BackgroundDocumentsSaver saveDocumentsScratch
INFO: Saving docs to scratch
```

**Comment by ryanhamilton** [comment]
Issue raised on call - qstudio downloads page says 40MB for linux/mac, it's actually 100MB
