### ISSUE TITLE
Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by ryanhamilton** [timeseries/qstudio#79]
Search emails for: "Unexpected end of ZLIB input stream"
I believe this occurs when there are 1000+ servers and it gets truncated by registry.

**Comment by ryanhamilton** [comment]
```
OS=Windows 10
Java=11.0.20
Des=unknown
Stack=java.lang.reflect.InvocationTargetException
        at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
        at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
        at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
        at com.timestored.qstudio.QStudioLauncher.main(QStudioLauncher.java:141)
Caused by: java.lang.AssertionError: java.io.EOFException: Unexpected end of ZLIB input stream
        at com.timestored.StringUtils.decompress(StringUtils.java:104)
        at com.timestored.connections.PreferenceHelper.decode(PreferenceHelper.java:50)
        at com.timestored.connections.ConnectionManager.reloadFromPreferences(ConnectionManager.java:689)
        at com.timestored.connections.ConnectionManager.setPreferenceStore(ConnectionManager.java:146)
        at com.timestored.qstudio.QStudioLauncher$2.launch(QStudioLauncher.java:227)
        at com.timestored.qstudio.QStudioLauncher$2.run(QStudioLauncher.java:143)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: [java.io](http://java.io/).EOFException: Unexpected end of ZLIB input stream
        at java.base/java.util.zip.InflaterInputStream.fill(Unknown Source)
        at java.base/java.util.zip.InflaterInputStream.read(Unknown Source)
        at java.base/java.io.FilterInputStream.read(Unknown Source)
        at com.timestored.StringUtils.decompress(StringUtils.java:100)
```

**Comment by ryanhamilton** [comment]
Few recommended actions and recovery options:

1. Ask a colleague to export their list of servers:
![image](https://github.com/user-attachments/assets/3c056e48-7729-4f52-8a77-087a4659be28)
MAKE SURE NO USERNAMES PASSWORDS ARE IN THE LIST

2. Use bulk server import to import into your qStudio. ``Server Menu`` -> ``Add Server List``.

![image](https://github.com/user-attachments/assets/3cc590a7-5247-4981-a84b-abd48fa63cb8)

3. Instead of adding usernames and passwords to the list, set a default for all connections. This makes it safer to share and removes the logins from every connection: ``Settings Menu``->``Preferences``

![image](https://github.com/user-attachments/assets/af6600d8-0865-4183-8ef7-3d4df7df0505)
